
:::{.callout-tip collapse="true" icon=false}
## Prise en main de la librairie `renv`

:::{.incremental}
0. Installer le package [`renv`](https://rstudio.github.io/renv/articles/renv.html)
1. Taper dans la console `renv::init()`, __lire le message__ et accepter.
2. Observer les nouveaux élements qui sont apparus dans le projet.
3. Installer le [package `gt`](https://gt.rstudio.com/) et observer le message dans la console.
4. Dans la partie sur les statistiques descriptives d'âge, ajouter ce code :

    ```r
    stats_age <- df %>%
      group_by(decennie = decennie_a_partir_annee(age)) %>%
      summarise(n())
    
    table_age <- gt::gt(stats_age) %>%
      gt::tab_header(
        title = "Distribution des âges dans notre population"
      ) %>%
      gt::fmt_number(
        columns = `n()`,
        sep_mark = " ",
        decimals = 0
      ) %>%
      gt::cols_label(
        decennie = "Tranche d'âge",
        `n()` = "Population"
      )

    ```

:::

:::

## Application 5B

:::{.callout-tip collapse="true" icon=false}
## Prise en main de la librairie `renv` (suite)

:::{.incremental style="margin-left: 30px;"}
5. Dans la console, faire `renv::status()` et observer le message.
6. Effectuer `renv::snapshot()` pour intégrer les nouveaux packages au *lockfile*
7. Faire un _commit_ et un _push_ des fichiers `script.R`, `.Rprofile`, `renv.lock` et du dossier `renv/`. _Push_.
8. Ouvrir un nouveau service `RStudio` sur le `SSPCloud` et cloner le projet dans les mêmes conditions que l'Application 0. Regarder les messages dans la console. 
9. Exécuter `renv::restore()` pour installer les packages nécessaires à l'exécution du projet.
10. Vérifier que le `script.R` s'exécute correctement dans ce nouvel environnement.
:::

:::

## Checkpoint

- [script.R](https://raw.githubusercontent.com/InseeFrLab/formation-bonnes-pratiques-R/main/R/checkpoints/application5b/script.R)
