## Application 0

:::{.callout-tip collapse="true" icon=false}
## Préparation de l'environnement de travail

:::{.incremental}
0. Si vous ne l'avez pas fait lors de la première partie de la formation, créer un compte sur [GitHub](https://github.com/) et [générer un *token*](https://docs.github.com/en/enterprise-server@3.4/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) (jeton d'accès) d'authentification
1. Créer un nouveau dépôt public sur [GitHub](https://github.com/)
2. Lancer un service `RStudio`. Dans l'onglet de configuration `Git` du service, fixer la durée du `Cache` pour le stockage des identifiants `GitHub` à une valeur suffisamment élevée
3. Cloner le dépôt distant sur votre environnement local (ici, le `RStudio` du `Datalab`):
    + `File` → `New project` → `Version Control` → `Git`
4. Créer un script `get_data.R` en copiant le contenu de [ce fichier](https://raw.githubusercontent.com/InseeFrLab/formation-bonnes-pratiques-R/main/R/get_data.R), puis l'exécuter
5. Créer le script `script.R` dans votre dépôt en copiant le contenu de [ce fichier](https://raw.githubusercontent.com/InseeFrLab/formation-bonnes-pratiques-R/main/R/script.R)
6. Ajouter la règle "individu_reg.*" au fichier `.gitignore`. Que signifie-t-elle ?
7. *Commit*/*push* les changements
:::

:::
