:::{.callout-tip collapse="true" icon=false}
## Introduction à la publication reproductible

:::{.incremental}
1. Cliquer sur `File > New file > Quarto document`:
    + Donner un titre et un.e auteur.e au rapport
    + Choisir `pdf` comme format de sortie
    + Décocher la case `Use visual markdown editor`
2. Sauvegarder le fichier sous le nom `report.qmd`.
3. Pour pouvoir générer un document `PDF`, une distribution de `LaTeX` est nécessaire.
Lancer la commande `tinytex::install_tinytex()` pour l'installer, puis redémarrer l'environnement R
(`File` -> `Quit Session`) pour mettre l'environnement à jour.
4. En vous inspirant du code d'exemple, modifier le fichier `report.qmd` pour :
    + Importer les fonctions du script `functions.R`
    + Importer les données avec la fonction `read_from_parquet`
    + Produire la table avec la fonction `produce_table_age`
Seuls le code utilisé et la table doivent appraître dans le rapport final.
5. Générer le rapport avec la touche `Render` et vérifier que l'*output* correspond à celui attendu.
:::

:::

## Checkpoint

- [report.qmd](https://raw.githubusercontent.com/InseeFrLab/formation-bonnes-pratiques-R/main/R/checkpoints/application7/report.qmd)
