name: Publish Git slides

on: 
  push:
    branches:
      - main
    paths:
      - "slides-git/"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: slides-git/index.qmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
